# THIS SCRIPT IS TO INSTALL LANDESY AGENT OVER WINDOWS MACHINES

# AS PER REQUIREMENT WE HAVE NOT PLACED THE INSTALLATION FILES OVER S3 OR GOOGLE DRIVE, RATHER STORED LOCALLY.
# IF REQUIRED , IT CAN BE PLACED UNDER ANY SECURE PLACE.
# IN THIS CASE, WE PLACED IT UNDER FILES/

#TEMPORARILY WE ARE CREATING A DIRECTORY TO STORE THE AGENT, ONCE INSTALLATION DONE SUCCESSFULLY, WE SHOULD DELETE IT.
- name: Create a temp directory
  win_file:
    path: C:\winzip
    state: directory

#WE CAN COPY THE ZIPPED AGENT FILES FROM LOCAL  TO REMOTE HOST TEMPORARY DIRECTORY CREATED ABOVE

- name: Copies the Zipped fils to remote locations on windows hosts
  win_copy:
     src:  /etc/ansible/roles/windows-landesk-without-status/files/winzip20xp.zip
     dest: C:\winzip\
     force: true

#ONCE FILE COPIED TO REMOTE HOST WE SHOULD UNZIP IT.

- name: unzipping the agent files on remote host.
  win_unzip:
     src: C:\winzip\winzip20xp.zip
     dest: C:\winzip\
#    rm: yes

#ONCE  UNZIP DONE WE CAN INSTALL THE .EXE FILE FROM THAT.
#
#============================== AGENT INSTALLATION WITHOUT STATUS====================================================
#
- name: Installing Windows Server Configuration.exe (WITHOUT STATUS:- Don't show GUI to the user)
  win_command: C:\winzip\winzip20xp.exe
  register: result
- debug: var=result
#- win_reboot: 
#    reboot_timeout_sec: 300
#  when: result.reboot_required
  
  ignore_errors: yes  
#  when: result.rc == '3010'
#  notify: windows_reboot
 
#============================== AGENT INSTALLATION WITH STATUS=============================
#
#- name: Installing Windows Server Configuration.exe (WITH STATUS:- shows GUI to the user)
#  win_command: C:\winzip\test\win_server_config_with_status.exe
#  register: result1
#- debug: var=result1
  
  
